# SpeedTeste
- alias: "Internet Speed ​​Glow Connect Ótimo"
  trigger:
    - platform: template
      value_template: "{{ states('sensor.speedtest_download')|float >= 10 }}"
  action:
    - service: shell_command.green
- alias: "Internet Speed ​​Glow Connect Fraco"
  trigger:
    - platform: template
      value_template: "{{ states('sensor.speedtest_download')|float < 10 }}"
  action:
    - service: shell_command.red