default_config:
#system_health:

# Historicos
history:

# Http 
http:
  api_password: !secret homeassistant_pwd

# map
map:

# Home Assistant
homeassistant:
  name: !secret home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  temperature_unit: C
  time_zone: America/Sao_Paulo
  packages: !include_dir_named packages



# Text to speech
tts:
  - platform: google_translate

# Influxdb database
influxdb:
  host: ia.joaopauloii
  port: 8086

# Sidebar Itens
panel_iframe:
  menu_nodered:
    title: 'Node-Red'
    url: 'http://localhost:1880'
    icon: mdi:sitemap

# Front end
frontend:
  javascript_version: latest

# Logs
logbook:
  exclude:
    entities:
      - sensor.last_boot
      - sensor.time
      - sensor.date




# Includes
device_tracker: !include_dir_merge_list device_tracker
sensor: !include_dir_merge_list sensor
group: !include_dir_merge_named group
automation: !include automations.yaml
script: !include scripts.yaml
