default_config:
#system_health:

# Historicos
history:

# Http 
http:
  api_password: !secret homeassistant_pwd

# map
map:

# Organizar a home
lovelace:

# Trabalha com Video
ffmpeg:

# hacs-work
hacs:
  token: !secret github_hacs-work_token
  python_script: True
  options:
    experimental: True

# Home Assistant
homeassistant:
  name: !secret home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  temperature_unit: C
  time_zone: America/Sao_Paulo
  packages: !include_dir_named packages

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Influxdb database
influxdb:
  host: ia.joaopauloii
  port: 8086
  include:
    entities:
      - sensor.disk_use
      - sensor.disk_use_percent
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      - sensor.last_boot

# Sidebar Itens
panel_iframe:
  menu_nodered:
    title: 'Node-Red'
    url: 'http://localhost:1880'
    icon: mdi:sitemap

# Front end
frontend:
  javascript_version: latest

# Logs
logbook:
  exclude:
    entities:
      - sensor.last_boot
      - sensor.time
      - sensor.date

# MQTT
mqtt:
  broker: !secret home_broker_ip
  port: !secret home_broker_port
  username: !secret home_broker_user
  password: !secret home_broker_pass

# TV Bravia
#media_player:
#  - platform: braviatv
#    host: !secret work_bravia_tv_ip
#    name: Bravia TV Work


# Includes
device_tracker: !include_dir_merge_list device_tracker/
switch: !include_dir_merge_list switches/
sensor: !include_dir_merge_list sensor/
group: !include_dir_merge_list group/
automation: !include automations.yaml
script: !include scripts.yaml

